### ISSUE TITLE
ImportError: cannot import name 'IPRange' from partially initialized module 'iprange

### ISSUE THREAD

**Issue by tianyu150** [lucasrodcosta/iprange-python#2]
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from iprange import IPRange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\conda\conda\envs\iprange\lib\site-packages\iprange\__init__.py", line 1, in <module>
    from iprange import IPRange
ImportError: cannot import name 'IPRange' from partially initialized module 'iprange' (most likely due to a circular import) (C:\Users\xxx\AppData\Local\conda\conda\envs\iprange\lib\site-packages\iprange\__init__.py)
>>>

**Comment by lucasrodcosta** [comment]
Hi @tianyu150. Thank you for submitting this issue.

I just released a new version (`0.0.9`) of the package.
Can you please check if it works now?
